; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Sun Dec 19 2021 15:02:44 GMT+0000 (Greenwich Mean Time)
M280 P0 S90 ; retract BLTouch

