; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Sun Dec 19 2021 15:02:45 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

